export const ChampionRole = {
  NUKER: "Nuker",
  DEBUFFER: "Debuffer",
  BUFFER: "Buffer",
  SPEED_BOOSTER: "Speed Booster",
  TM_REDUCER: "TM Reducer",
  HEALER: "Healer",
  CONTROL: "CC",
  REVIVER: "Reviver",
  CAMPAIGN_FARMER: "Campaign Farmer",
  DEMON_LORD: "Demon Lord",
  HYDRA: "Hydra",
  CHIMERA: "Chimera",
  BOSS_KILLER: "Boss Killer",
  UNKILLABLE: "Unkillable",
  POISONER: "Poisoner",
  HP_BURNER: "HP Burner",
  MAX_HP_DPS: "Max HP DPS",
  ARENA: "Arena",
  CLEANSER: "Cleanser",
  BLOCK_BUFF: "Block Buff",
  DOOM_TOWER: "Doom Tower",
} as const;

export const ChampionRoleImageMap: Record<ChampionRole, string> = {
  Nuker: "img/roles/nuker.png",
  Debuffer: "img/roles/debuffer.png",
  Buffer: "img/roles/buffer.png",
  "Speed Booster": "img/roles/speed_booster.png",
  "TM Reducer": "img/roles/tm_reduction.jpg",
  Healer: "img/roles/healer.png",
  CC: "img/roles/cc.avif",
  Reviver: "img/roles/reviver.png",
  "Campaign Farmer": "img/roles/campaign_farmer.png",
  "Demon Lord": "img/roles/demon_lord.png",
  Hydra: "img/roles/hydra.png",
  Chimera: "img/roles/chimera.png",
  "Boss Killer": "img/roles/boss_killer.png",
  Unkillable: "img/roles/unkillable.png",
  Poisoner: "img/roles/poisoner.png",
  "HP Burner": "img/roles/hp_burner.png",
  "Max HP DPS": "img/roles/max_hp_damage.png",
  Arena: "img/roles/arena.png",
  Cleanser: "img/roles/cleanser.png",
  "Block Buff": "img/roles/Block-buffs.webp",
  "Doom Tower": "img/roles/doom_tower.png",
};

export type ChampionRole = (typeof ChampionRole)[keyof typeof ChampionRole];
