export const ChampionRole = {
  NUKER: "Nuker",
  DEBUFFER: "Debuffer",
  BUFFER: "Buffer",
  SPEED_BOOSTER: "Speed Booster",
  TM_REDUCER: "TM Reducer",
  HEALER: "Healer",
  CONTROL: "CC",
  REVIVER: "Reviver",
  CAMPAIGN_FARMER: "Campaign Farmer",
  DEMON_LORD: "Demon Lord",
  HYDRA: "Hydra",
  CHIMERA: "Chimera",
  BOSS_KILLER: "Boss Killer",
  UNKILLABLE: "Unkillable",
  POISONER: "Poisoner",
  HP_BURNER: "HP Burner",
  MAX_HP_DPS: "Max HP DPS",
  ARENA: "Arena",
  CLEANSER: "Cleanser",
  BLOCK_BUFF: "Block Buff",
  DOOM_TOWER: "Doom Tower",
  PROVOKER: "Provoker",
  LEECH: "Leech",
  SHIELDER: "Shielder",
  SLEEP_DEBUFFER: "Sleep Debuffer",
  DECREASE_ATK: "Decrease ATK",
  DECREASE_DEF: "Decrease DEF",
  WEAKEN: "Weaken",
  DECREASE_SPD: "Decrease SPD",
  POISON_ACTIVATOR: "Poison Activator",
  HP_BURN_ACTIVATOR: "HP Burn Activator",
  TM_BOOSTER: "TM Boost",
  BUFF_STRIP: "Buff Strip",
  ALLY_ATTACK: "Ally Attack",
  INCREASE_ATK: "Increase ATK",
  INCREASE_ACC: "Increase ACC",
  INCREASE_DEF: "Increase DEF",
  STRENGTHEN: "Strengthen",
  FREEZE: "Freeze",
  STUN: "Stun",
  COUNTERATTACK: "Counterattack",
  ALLY_PROTECTION: "Ally Protection",
  HEAL_ON_DEATH: "Heal on Death",
  MULTI_HITTER: "Multi Hitter",

  // ── Additional buffs ──
  BLOCK_DAMAGE: "Block Damage",
  BLOCK_DEBUFFS: "Block Debuffs",
  BONE_ARMOR: "Bone Armor",
  CONTINUOUS_HEAL: "Continuous Heal",
  ECLIPSE: "Eclipse",
  ETERNAL_RAGE: "Eternal Rage",
  FERVOR: "Fervor",
  FORTIFY: "Fortify",
  GOLDPLATED: "Goldplated",
  IMMUTABLE: "Immutable",
  INCREASE_C_DMG: "Increase C.DMG",
  INCREASE_C_RATE: "Increase C.RATE",
  INCREASE_RES: "Increase RES",
  INTERCEPT: "Intercept",
  LIFE_BARRIER: "Life Barrier",
  LIGHTNING_ORB: "Lightning Orb",
  MAGMA_SHIELD: "Magma Shield",
  POISON_CLOUD: "Poison Cloud",
  RAGE: "Rage",
  REFLECT_DAMAGE: "Reflect Damage",
  SERPENTS_WILL: "Serpent's Will",
  SHATTER: "Shatter",
  STONE_SKIN: "Stone Skin",
  STORMCALL: "Stormcall",
  TAUNT: "Taunt",
  TOTAL_GUARD: "Total Guard",
  VEIL: "Veil",
  VENGEANCE: "Vengeance",

  // ── Additional debuffs ──
  BERSERK: "Berserk",
  BLOCK_ACTIVE_SKILLS: "Block Active Skills",
  BLOCK_PASSIVE_SKILLS: "Block Passive Skills",
  BLOCK_REVIVE: "Block Revive",
  BOMB: "Bomb",
  DAZED: "Dazed",
  DEATHBRAND: "Deathbrand",
  DECAPITATED: "Decapitated",
  DECREASE_ACC: "Decrease ACC",
  DECREASE_C_DMG: "Decrease C.DMG",
  DECREASE_C_RATE: "Decrease C.RATE",
  DECREASE_RES: "Decrease RES",
  ENFEEBLE: "Enfeeble",
  ENSNARE: "Ensnare",
  ENTANGLE: "Entangle",
  FATIGUE: "Fatigue",
  FEAR: "Fear",
  HEAL_REDUCTION: "Heal Reduction",
  HEX: "Hex",
  HUNTERS_GAZE: "Hunter's Gaze",
  INFEST: "Infest",
  IRONBRAND: "Ironbrand",
  NECROSIS: "Necrosis",
  NULLIFY: "Nullify",
  PAIN_LINK: "Pain Link",
  PETRIFICATION: "Petrification",
  POISON_SENSITIVITY: "Poison Sensitivity",
  SEAL: "Seal",
  SHEEP: "Sheep",
  SIPHON: "Siphon",
  SMITE: "Smite",
} as const;

export const ChampionRoleImageMap: Record<ChampionRole, string> = {
  Nuker: "img/roles/nuker.png",
  Debuffer: "img/roles/debuffer.png",
  Buffer: "img/roles/buffer.png",
  "Speed Booster": "img/roles/speed_booster.png",
  "TM Reducer": "img/roles/tm_reduction.jpg",
  Healer: "img/roles/healer.png",
  CC: "img/roles/cc.avif",
  Reviver: "img/roles/reviver.png",
  "Campaign Farmer": "img/roles/campaign_farmer.png",
  "Demon Lord": "img/roles/demon_lord.png",
  Hydra: "img/roles/hydra.png",
  Chimera: "img/roles/chimera.png",
  "Boss Killer": "img/roles/boss_killer.png",
  Unkillable: "img/roles/unkillable.png",
  Poisoner: "img/roles/poisoner.png",
  "HP Burner": "img/roles/hp_burner.png",
  "Max HP DPS": "img/roles/max_hp_damage.png",
  Arena: "img/roles/arena.png",
  Cleanser: "img/roles/cleanser.png",
  "Block Buff": "img/roles/Block-buffs.webp",
  "Doom Tower": "img/roles/doom_tower.png",
  Provoker: "img/debuffs/Provoke.png",
  Leech: "img/debuffs/Leech.png",
  Shielder: "img/buffs/Shield.png",
  "Sleep Debuffer": "img/debuffs/Sleep.png",
  "Decrease ATK": "img/debuffs/Decrease ATK.png",
  "Decrease DEF": "img/debuffs/Decrease DEF.png",
  Weaken: "img/debuffs/Weaken.png",
  "Decrease SPD": "img/debuffs/Decrease SPD.png",
  "Poison Activator": "img/debuffs/Poison.png",
  "HP Burn Activator": "img/debuffs/HP Burn.png",
  "TM Boost": "img/buffs/TM Boost.png",
  "Buff Strip": "img/debuffs/Block Buffs.png",
  "Ally Attack": "img/buffs/Couterattack.png",
  "Increase ATK": "img/buffs/Increase ATK.png",
  "Increase ACC": "img/buffs/Increase ACC.png",
  "Increase DEF": "img/buffs/Increase DEF.png",
  Strengthen: "img/buffs/Strengthen.png",
  Freeze: "img/debuffs/Freeze.png",
  Stun: "img/debuffs/Stun.png",
  Counterattack: "img/buffs/Couterattack.png",
  "Ally Protection": "img/buffs/Ally Protector.png",
  "Heal on Death": "img/buffs/Continuous Heal.png",
  "Multi Hitter": "img/roles/nuker.png",

  // ── Additional buffs ──
  "Block Damage": "img/buffs/Block Damage.png",
  "Block Debuffs": "img/buffs/Block Debuffs.png",
  "Bone Armor": "img/buffs/Bone Armor.png",
  "Continuous Heal": "img/buffs/Continuous Heal.png",
  Eclipse: "img/buffs/Eclipse.png",
  "Eternal Rage": "img/buffs/Eternal Rage.png",
  Fervor: "img/buffs/Fervor.png",
  Fortify: "img/buffs/Fortify.png",
  Goldplated: "img/buffs/Goldplated.png",
  Immutable: "img/buffs/Immutable.png",
  "Increase C.DMG": "img/buffs/Increase C DMG.png",
  "Increase C.RATE": "img/buffs/Increase C Rate.png",
  "Increase RES": "img/buffs/Increase RES.png",
  Intercept: "img/buffs/Intercept.png",
  "Life Barrier": "img/buffs/Life Barrier.png",
  "Lightning Orb": "img/buffs/Lightning Orb.png",
  "Magma Shield": "img/buffs/Magma Shield.png",
  "Poison Cloud": "img/buffs/Poison Cloud.png",
  Rage: "img/buffs/Rage.png",
  "Reflect Damage": "img/buffs/Reflect Damage.png",
  "Serpent's Will": "img/buffs/Serpents Will.png",
  Shatter: "img/buffs/Shatter.png",
  "Stone Skin": "img/buffs/Stone Skin.png",
  Stormcall: "img/buffs/Stormcall.png",
  Taunt: "img/buffs/Taunt.png",
  "Total Guard": "img/buffs/Total Guard.png",
  Veil: "img/buffs/Veil.png",
  Vengeance: "img/buffs/Vengence.png",

  // ── Additional debuffs ──
  Berserk: "img/debuffs/Berserk.png",
  "Block Active Skills": "img/debuffs/Block Active Skills.png",
  "Block Passive Skills": "img/debuffs/Block Passive Skills.png",
  "Block Revive": "img/debuffs/BlockRevive.png",
  Bomb: "img/debuffs/Bomb.png",
  Dazed: "img/debuffs/Dazed.png",
  Deathbrand: "img/debuffs/Deathbrand.png",
  Decapitated: "img/debuffs/Decapitated.png",
  "Decrease ACC": "img/debuffs/Decrease ACC.png",
  "Decrease C.DMG": "img/debuffs/Decrease C DMG.png",
  "Decrease C.RATE": "img/debuffs/Decrease C Rate.png",
  "Decrease RES": "img/debuffs/Decrease RES.png",
  Enfeeble: "img/debuffs/Enfeeble.png",
  Ensnare: "img/debuffs/Ensnare.png",
  Entangle: "img/debuffs/Entangle.png",
  Fatigue: "img/debuffs/Fatigue.png",
  Fear: "img/debuffs/Fear.png",
  "Heal Reduction": "img/debuffs/Heal Reduction.png",
  Hex: "img/debuffs/Hex.png",
  "Hunter's Gaze": "img/debuffs/Hunters Gaze.png",
  Infest: "img/debuffs/Infest.png",
  Ironbrand: "img/debuffs/Ironbrand.png",
  Necrosis: "img/debuffs/Necrosis.png",
  Nullify: "img/debuffs/Nullify.png",
  "Pain Link": "img/debuffs/Pain Link.png",
  Petrification: "img/debuffs/Petrification.png",
  "Poison Sensitivity": "img/debuffs/Poison Sensitivity.png",
  Seal: "img/debuffs/Seal.png",
  Sheep: "img/debuffs/Sheep.png",
  Siphon: "img/debuffs/Siphon.png",
  Smite: "img/debuffs/Smite.png",
};

export type ChampionRole = (typeof ChampionRole)[keyof typeof ChampionRole];
